services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    container_name: redis-container
    restart: always

    command: ["redis-server", "--appendonly", "yes"]

  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: mssql-container
    restart: always
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - mssql_data:/var/opt/mssql

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-container
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-container
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

volumes:
  mssql_data: